---
- name: Haproxy deployment
  any_errors_fatal: true
  hosts: localhost
  tasks:
      - name: Building image
        command: docker build . -t allezon-haproxy:latest

      - name: Starting container
        command: docker run -d --network=host allezon-haproxy:latest