---
- name: Aerospike install
  any_errors_fatal: true
  hosts: aerospike

  tasks:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Create aerospike config directory
      become: true
      file:
        path: /opt/aerospike/etc
        state: directory

    - name: Copy config file with owner and permissions
      become: true
      register: service_conf
      template:
        src: aerospike.conf.j2
        dest: /opt/aerospike/etc/aerospike.conf
        owner: root
        group: root
        mode: '0644'

    - name: Remove previous container
      become: true
      become_user: root
      command: docker rm -f aerospike

    - name: Run new container
      become: true
      become_user: root
      command: docker run -d -v /opt/aerospike/etc/:/opt/aerospike/etc/ --name aerospike -p 3000-3002:3000-3002 aerospike/aerospike-server --config-file /opt/aerospike/etc/aerospike.conf

    - name: Increase batch request queue
      become: true
      become_user: root
      command: docker exec -ti aerospike asinfo -v "set-config:context=service;batch-max-buffers-per-queue=8192"
